Repository kiwiproject/kiwi, pull requests merged in 2021-12, with the labels that each got.

#637 Locate ansible-vault command in VaultEncryptionHelperIntegrationTest
  src/test/java/org/kiwiproject/ansible/vault/VaultEncryptionHelperIntegrationTest.java
Labels: enhancement

#650 Add bom
  .github/dependabot.yml
  pom.xml
Labels: dependencies

#651 Bump kiwi-bom from 0.1.0 to 0.2.0
  pom.xml
Labels: dependencies, java

#652 Update parent etc
  pom.xml
Labels: dependencies
