Repository kiwiproject/kiwi, pull requests merged in 2021-04, with the labels that each got.

#533 Bump kiwi-parent from 0.9.0 to 0.10.0
  pom.xml
Labels: dependencies

#541 Move IntStreams from kiwi-test to kiwi
  src/main/java/org/kiwiproject/stream/IntStreams.java
  src/test/java/org/kiwiproject/stream/IntStreamsTest.java
Labels: new feature

#542 Deprecate JDBI 2 modules
  src/main/java/org/kiwiproject/dropwizard/jdbi2/Jdbi2Builders.java
  src/main/java/org/kiwiproject/jdbi2/sqlobject/BindJSONB.java
Labels: code cleanup

#545 Remove several redundant suppression comments
  src/test/java/org/kiwiproject/dropwizard/jdbi3/Jdbi3BuildersTest.java
  src/test/java/org/kiwiproject/hibernate/usertype/JSONBUserTypeUnitTest.java
Labels: code cleanup

#546 Setup build for Java 11 and 16
  .github/workflows/build.yml
Labels: enhancement

#549 Sonar: Cleanup JsonHelper#mergeNodes and add additional tests
  src/main/java/org/kiwiproject/json/JsonHelper.java
  src/test/java/org/kiwiproject/json/JsonHelperAdvancedFeaturesTest.java
Labels: code cleanup

#550 Bump GitHub cache action version from 2.1.4 to 2.1.5
  .github/workflows/build.yml
Labels: dependencies
